---
apiVersion: v1
kind: Pod
metadata:
  name: example-service-s3-datastore
  annotations:
    iam.amazonaws.com/role: k8s-OverrideName-Stage-ExecutionRole
spec:
  containers:
    - command:
        - sleep
        - "3600"
      image: amazon/aws-cli:latest
      name: aws
      resources:
        limits:
          cpu: "100m"
          memory: "200Mi"
      env:
        - name: "s3_bucket"
          value: "s3-datastore.stage-example-com"
  restartPolicy: "Never"