---
apiVersion: v1
kind: Pod
metadata:
  name: example-service-dynamodb-datastore
  annotations:
    iam.amazonaws.com/role: k8s-Dynamodb-Stage-ExecutionRole
spec:
  containers:
    - command:
        - sleep
        - "3600"
      image: amazon/aws-cli:latest
      name: aws
      resources:
        limits:
          cpu: "100m"
          memory: "200Mi"
      env:
        - name: "dynamodb_table_name"
          value: ""
  restartPolicy: "Never"